services:
  backend:
    image: ghcr.io/dangreen07/music-streaming-backend:main
    # build : ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DO_ACCESS_KEY_ID: ${DO_ACCESS_KEY_ID}
      DO_SECRET_ACCESS_KEY: ${DO_SECRET_ACCESS_KEY}
      DO_REGION: ${DO_REGION}
      DO_ENDPOINT: ${DO_ENDPOINT}
      DO_BUCKET_NAME: ${DO_BUCKET_NAME}
  frontend:
    build : ./frontend
    ports:
      - "3000:3000"
    links:
      - "backend:localhost"
    environment:
      SERVER_URL: ${SERVER_URL}
      CLOUDFRONT_URL: ${CLOUDFRONT_URL}
      SERVER_URL_FROM_SERVER: "http://backend:8080"
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'true'
