services:
  backend:
    build : ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
  frontend:
    build : ./frontend
    ports:
      - "3000:3000"
    links:
      - "backend:localhost"
    environment:
      SERVER_URL: ${SERVER_URL}
      SERVER_URL_FROM_SERVER: "http://backend:8080"
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'true'
